import localFont from 'next/font/local';
import './globals.css';
import { Metadata } from 'next';
import Header from '@/components/header';
import Hero from '@/components/hero';
import Footer from '@/components/footer';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Food',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header />
        {true && <Hero />}
        <main className="w-4/5 m-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
