import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Food',
  description: 'Generated by create next app',
};

export default function DashboardPage() {
  return <h1 className="bg-red-500">Dashboard User</h1>;
}
