import Header from '@/components/header';
import { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Food',
  description: 'Generated by create next app',
};

export default function DashboardPage() {
  return (
    <div className="w-4/5 m-auto">
      <Header />
    </div>
  );
}
