import type { Metadata } from 'next';
import '../globals.css';

export const metadata: Metadata = {
  title: 'Food',
  description: 'Generated by create next app',
};

export default function LayoutUser({ children }: { children: React.ReactNode }) {
  return <main>{children}</main>;
}
